set-option -g default-terminal "tmux-256color"
set-option -a terminal-overrides ',*:RGB'
set -g set-clipboard on

# add mouse support 
set -g mouse on

set-window-option -g mode-keys vi

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set -g status-style "fg=color15 bg=default"
set -g window-status-style "fg=color7"
set -g window-status-current-style "fg=color11"

# custom keybinds
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
    