#!/usr/bin/sh

option=$(printf "  Shutdown\n  Reboot\n󰍃  Logout\n󰤄  Suspend\n  Lock" | wofi -dmenu -i -theme-str 'inputbar {children: [entry];} listview {lines: 5;}')

case "$option" in
	"  Shutdown") 
		poweroff;;
	"  Reboot") 
		reboot;;
	"󰍃  Logout")
		i3-msg exit;;
	"󰤄  Suspend")
		systemctl suspend;;
	"  Lock")
		lockscreen;;
	*) 
		exit 1;;
esac


